const std = @import("std");
const builtin = @import("builtin");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    _ = b.addModule("cpp_bindgen", .{
        .root_source_file = b.path("src/root.zig"),
        .target = target,
    });

    const test_step = b.step("test", "Run tests");
    test_step.dependOn(addTests(b, target, optimize, "test"));
    test_step.dependOn(addGlueTests(b, target, optimize, "test-inline"));

    // Also exercise the MSVC ABI on a Windows x86_64 host (needs MSVC + SDK).
    if (builtin.os.tag == .windows and builtin.cpu.arch == .x86_64) {
        const msvc_target = b.resolveTargetQuery(.{ .cpu_arch = .x86_64, .os_tag = .windows, .abi = .msvc });
        const msvc_step = b.step("test-msvc", "Run tests against the MSVC ABI (Windows x86_64 host only)");
        msvc_step.dependOn(addTests(b, msvc_target, optimize, "test-msvc"));
        msvc_step.dependOn(addGlueTests(b, msvc_target, optimize, "test-inline-msvc"));
    }
}

/// How to generate the C++ glue for a bindings module. See `src/emit.zig` for
/// what ends up in it.
pub const GlueOptions = struct {
    /// The module the generated C++ is compiled into. It inherits that
    /// module's include paths, which is what lets the glue find the headers.
    attach_to: *std.Build.Module,
    /// Where the scan starts. Pass the same module object your own code
    /// imports the bindings from: a source file may belong to only one
    /// module. Files it publicly re-exports are scanned too, so
    /// `pub const string = @import("string.zig");` is all a second binding
    /// file needs.
    binding_module: *std.Build.Module,
    /// `#include` lines for the glue, verbatim and in order. A bare name is
    /// quoted; one already spelled `<vector>` or `"x.h"` is taken as written.
    headers: []const []const u8 = &.{},
    /// Extra flags for the glue, appended to the mandatory ones. Give it the
    /// same defines as the rest of your C++: the facts it checks are only the
    /// facts that will be linked if it sees the same declarations.
    flags: []const []const u8 = &.{},
    /// The target the glue is generated for. The generator runs on the build
    /// machine, so this has to be a target the build machine can execute; it
    /// is built for the target rather than for the host because the sizes and
    /// offsets it checks are the target's.
    target: std.Build.ResolvedTarget,
    name: []const u8 = "cpp-glue",
};

/// Generates the C++ glue for a bindings module and compiles it into
/// `attach_to`. The bindings themselves hold nothing but types and
/// signatures; everything the glue needs is here.
///
/// ```zig
/// const cpp_bindgen = @import("cpp_bindgen");            // in build.zig
/// const dep = b.dependency("cpp_bindgen", .{ .target = target });
///
/// const bindings = b.createModule(.{ .root_source_file = b.path("src/bindings.zig"), .target = target });
/// bindings.addImport("cpp_bindgen", dep.module("cpp_bindgen"));
/// exe_mod.addImport("bindings", bindings);
///
/// cpp_bindgen.addCppGlue(b, dep, .{
///     .attach_to = exe_mod,
///     .binding_module = bindings,
///     .headers = &.{"ofMain.h"},
///     .target = target,
/// });
/// ```
pub fn addCppGlue(b: *std.Build, dep: *std.Build.Dependency, opts: GlueOptions) void {
    generateGlue(b, dep.path("tools/emit.zig"), dep.module("cpp_bindgen"), opts);
}

/// `-fno-inline` is load-bearing: a constructor has no address to take, so the
/// glue can only name one by constructing an object, and an optimizer that
/// inlines that call drops the out-of-line copy the linker needs.
const glue_flags: []const []const u8 = &.{ "-std=c++17", "-fno-inline", "-Wno-invalid-offsetof" };

fn generateGlue(b: *std.Build, tool: std.Build.LazyPath, cpp_bindgen: *std.Build.Module, opts: GlueOptions) void {
    // The manifest is generated rather than written by hand, so a binding
    // file carries no build metadata at all.
    const manifest = b.createModule(.{ .root_source_file = writeManifest(b, opts), .target = opts.target });
    manifest.addImport("cpp_bindgen", cpp_bindgen);
    manifest.addImport("bindings", opts.binding_module);

    const gen = b.createModule(.{ .root_source_file = tool, .target = opts.target });
    gen.addImport("cpp_bindgen", cpp_bindgen);
    gen.addImport("manifest", manifest);

    const run = b.addRunArtifact(b.addExecutable(.{ .name = opts.name, .root_module = gen }));
    const glue = run.addOutputFileArg("cpp_glue.cpp");

    const flags = b.allocator.alloc([]const u8, glue_flags.len + opts.flags.len) catch @panic("OOM");
    @memcpy(flags[0..glue_flags.len], glue_flags);
    @memcpy(flags[glue_flags.len..], opts.flags);
    opts.attach_to.addCSourceFile(.{ .file = glue, .flags = flags });
}

fn writeManifest(b: *std.Build, opts: GlueOptions) std.Build.LazyPath {
    var text: []const u8 =
        \\// Generated by cpp-bindgen's build.zig. Do not edit.
        \\const cpp = @import("cpp_bindgen");
        \\
        \\pub const cpp_manifest: cpp.emit.Manifest = .{
        \\    .headers = &.{
        \\
    ;
    for (opts.headers) |h| text = b.fmt("{s}        \"{f}\",\n", .{ text, std.zig.fmtString(h) });
    return b.addWriteFiles().add("cpp_manifest.zig", b.fmt(
        \\{s}    }},
        \\    .modules = &.{{@import("bindings")}},
        \\}};
        \\
    , .{text}));
}

fn addTests(b: *std.Build, target: std.Build.ResolvedTarget, optimize: std.builtin.OptimizeMode, name: []const u8) *std.Build.Step {
    const is_msvc = target.result.abi == .msvc;
    const mod = b.createModule(.{
        .root_source_file = b.path("src/root.zig"),
        .target = target,
        .optimize = optimize,
        .link_libcpp = !is_msvc,
    });
    mod.addCSourceFile(.{
        .file = b.path("test/fixture.cpp"),
        // `-fno-inline` for the same reason the glue needs it: an optimized
        // build drops a compiler-generated helper nothing references
        // out of line, and MSVC's vbase destructor (`??_D`) is one.
        // The MSVC build also links no C++ runtime: drop the libc++ autolink
        // and RTTI.
        .flags = if (is_msvc)
            &.{ "-std=c++17", "-fno-inline", "-fno-autolink", "-fno-rtti" }
        else
            &.{ "-std=c++17", "-fno-inline" },
    });
    const tests = b.addTest(.{ .name = name, .root_module = mod });
    return &b.addRunArtifact(tests).step;
}

/// End to end: generate the glue for `test/inline_fixture.zig`, compile it
/// into a test binary, and call the header-only C++ it binds. A missing
/// definition fails at link time, and a wrong layout fails in the C++
/// compiler before that.
fn addGlueTests(b: *std.Build, target: std.Build.ResolvedTarget, optimize: std.builtin.OptimizeMode, name: []const u8) *std.Build.Step {
    const is_msvc = target.result.abi == .msvc;
    const lib = b.createModule(.{ .root_source_file = b.path("src/root.zig"), .target = target });
    const bindings = b.createModule(.{ .root_source_file = b.path("test/inline_fixture.zig"), .target = target });
    bindings.addImport("cpp_bindgen", lib);

    const mod = b.createModule(.{
        .root_source_file = b.path("test/inline_test.zig"),
        .target = target,
        .optimize = optimize,
        .link_libcpp = !is_msvc,
    });
    mod.addImport("cpp_bindgen", lib);
    mod.addImport("inline_fixture", bindings);
    mod.addIncludePath(b.path("test"));

    // This build links no C++ runtime, because the MSVC one is not on a
    // search path Zig sets up; `Shape`'s virtual destructor needs the
    // deleting form, which calls `operator delete`.
    if (is_msvc) mod.addCSourceFile(.{
        .file = b.path("test/msvc_support.cpp"),
        .flags = &.{ "-std=c++17", "-fno-autolink", "-fno-rtti" },
    });

    generateGlue(b, b.path("tools/emit.zig"), lib, .{
        .attach_to = mod,
        .binding_module = bindings,
        .headers = &.{"inline_fixture.hpp"},
        .flags = if (is_msvc) &.{ "-fno-autolink", "-fno-rtti" } else &.{},
        .target = target,
        .name = b.fmt("{s}-glue", .{name}),
    });

    const tests = b.addTest(.{ .name = name, .root_module = mod });
    return &b.addRunArtifact(tests).step;
}
