//! Emits a C++ translation unit that does two things the Zig side cannot do
//! for itself:
//!
//! 1. Forces a definition to exist for every entity a binding names. A class
//!    template specialization, an inline function, an inline member: each has
//!    no symbol until some translation unit emits one, and a header alone
//!    never does. The glue is that translation unit.
//! 2. Checks, in the C++ compiler, that every Zig type standing for a C++
//!    class has the size, alignment, member offsets, and ABI category that
//!    the class really has. `cpp-bindgen` reads no headers, so these are the
//!    facts a binding gets wrong; a `static_assert` turns a silent memory
//!    corruption into a compile error.
//!
//! `render` builds the whole file as a comptime string. A generator binary
//! (`tools/emit.zig`) writes it out, and `addCppGlue` in `build.zig` compiles
//! it into the same build as the bindings.
const std = @import("std");
const cpp = @import("root.zig");
const ctype = @import("ctype.zig");
const cppsrc = @import("cppsrc.zig");

const CType = ctype.CType;
const Signature = cpp.Signature;

/// What to emit. `modules` are file structs, as returned by `@import`; every
/// public declaration in them is scanned for a type carrying `cpp_name` or
/// `cpp_template`, and for a `Signature` constant.
pub const Manifest = struct {
    /// `#include` lines, verbatim and in order: `"ofMain.h"`, `<vector>`.
    headers: []const []const u8 = &.{},
    /// Modules to scan. Only public declarations are visible.
    modules: []const type = &.{},
    /// Types to include beyond what scanning finds.
    types: []const type = &.{},
    /// Signatures to force a definition for, beyond what scanning finds.
    /// A function that is not header-only needs no entry: its own translation
    /// unit already defines it.
    functions: []const Signature = &.{},
    /// C++ inserted after the headers, for a `#define` or a `using`.
    prelude: []const u8 = "",
};

// Declarations a Zig type may carry to steer the glue:
//
// - `cpp_no_instantiate: bool`: do not explicitly instantiate this class
//   template specialization. Explicit instantiation instantiates *every*
//   member, including ones that do not compile for these template arguments,
//   which is a real hazard for a standard-library container.
// - `cpp_no_offsets: bool`: check size and alignment but not member offsets.
//
// A field whose name starts with `_` is not checked: that is how a binding
// spells a vtable pointer, a virtual base, or tail padding, none of which is
// a C++ member that `offsetof` can name.

/// The whole glue translation unit.
pub fn render(comptime m: Manifest) []const u8 {
    @setEvalBranchQuota(1 << 30);
    const types = comptime collectTypes(m);
    const fns = comptime collectFns(m);

    comptime var out: []const u8 =
        \\// Generated by cpp-bindgen. Do not edit; edit the bindings instead.
        \\//
        \\// Compile this with the same compiler, flags, and headers as the C++ it
        \\// binds, or the facts it checks are not the facts that will be linked.
        \\
        \\
    ;
    inline for (m.headers) |h| out = out ++ "#include " ++ include(h) ++ "\n";
    // offsetof needs a declaration, and no C++ header is guaranteed here.
    out = out ++ "#include <stddef.h>\n";
    if (m.prelude.len > 0) out = out ++ "\n" ++ m.prelude ++ "\n";

    // Aliases first: they name each class once, so the checks and the stubs
    // below stay readable however long a template-id is.
    out = out ++ "\n// Every C++ class a binding names.\n";
    inline for (types, 0..) |t, i| out = out ++ "typedef " ++ cppsrc.pathName(t.info.path) ++ " " ++ alias(i) ++ ";\n";

    out = out ++ instantiations(types);
    out = out ++ definitions(fns, types);
    out = out ++ checks(types);
    return out;
}

fn include(comptime h: []const u8) []const u8 {
    // A header already spelled `<...>` or `"..."` is taken as written.
    if (h.len > 0 and (h[0] == '<' or h[0] == '"')) return h;
    return "\"" ++ h ++ "\"";
}

fn alias(comptime i: usize) []const u8 {
    return "cppbindgen_t" ++ ctype.decimal(i);
}

/// A scanned type: the Zig type and what `ctype` made of it.
const Entry = struct {
    T: type,
    info: CType.Named,
    /// The specialization is explicitly instantiated.
    instantiate: bool,
    /// Member offsets are checked.
    offsets: bool,
};

fn collectTypes(comptime m: Manifest) []const Entry {
    comptime var out: []const Entry = &.{};
    inline for (m.modules) |mod| {
        inline for (@typeInfo(mod).@"struct".decl_names) |name| {
            const T = @field(mod, name);
            if (@TypeOf(T) != type) continue;
            if (!isClassLike(T)) continue;
            if (!@hasDecl(T, "cpp_name") and !@hasDecl(T, "cpp_template")) continue;
            out = addType(out, T);
        }
    }
    inline for (m.types) |T| out = addType(out, T);
    return out;
}

fn isClassLike(comptime T: type) bool {
    return switch (@typeInfo(T)) {
        .@"struct", .@"union", .@"enum", .@"opaque" => true,
        else => false,
    };
}

fn addType(comptime list: []const Entry, comptime T: type) []const Entry {
    const t = ctype.fromZig(T);
    if (t != .named) @compileError(@typeName(T) ++ ": not a C++ class type");
    // Two Zig types may describe one C++ class; the class is checked once.
    inline for (list) |e| if (std.mem.eql(u8, ctype.pathKey(e.info.path), ctype.pathKey(t.named.path))) return list;
    const templated = t.named.path[t.named.path.len - 1].args.len > 0;
    return list ++ &[_]Entry{.{
        .T = T,
        .info = t.named,
        .instantiate = templated and t.named.kind != .@"enum" and !flag(T, "cpp_no_instantiate"),
        .offsets = !flag(T, "cpp_no_offsets"),
    }};
}

fn flag(comptime T: type, comptime name: []const u8) bool {
    return @hasDecl(T, name) and @field(T, name);
}

fn collectFns(comptime m: Manifest) []const ctype.Function {
    comptime var out: []const ctype.Function = &.{};
    inline for (m.modules) |mod| {
        inline for (@typeInfo(mod).@"struct".decl_names) |name| {
            const d = @field(mod, name);
            if (@TypeOf(d) != Signature) continue;
            out = out ++ &[_]ctype.Function{cpp.describe(d)};
        }
    }
    inline for (m.functions) |sig| out = out ++ &[_]ctype.Function{cpp.describe(sig)};
    return out;
}

/// `template struct tpl::vec<3, float, (tpl::qualifier)1>;` — the one
/// construct that emits a whole specialization, members included.
fn instantiations(comptime types: []const Entry) []const u8 {
    comptime var out: []const u8 = "";
    inline for (types) |e| {
        if (!e.instantiate) continue;
        out = out ++ "template " ++ cppsrc.kindKeyword(e.info.kind) ++ " " ++ cppsrc.pathName(e.info.path) ++ ";\n";
    }
    if (out.len == 0) return "";
    return "\n// Class template specializations, instantiated here so their\n" ++
        "// members exist as symbols.\n" ++ out;
}

/// Forces a definition for each named function. Taking a function's address
/// from a variable with external linkage is the only form that survives
/// optimization: a call can be inlined, after which the out-of-line copy of
/// an inline function is dead and is dropped. Constructors, destructors, and
/// virtual functions have no usable address, so they get a stub instead, and
/// the glue must be compiled with `-fno-inline` for those to survive.
fn definitions(comptime fns: []const ctype.Function, comptime types: []const Entry) []const u8 {
    comptime var out: []const u8 = "";
    inline for (fns, 0..) |f, i| {
        const name = "cppbindgen_f" ++ ctype.decimal(i);
        out = out ++ switch (f.special) {
            .ctor => ctorStub(f, types, name),
            .dtor => dtorStub(f, types, name),
            .none => if (f.is_virtual) virtualStub(f, types, name) else pointerDecl(f, name),
        } ++ "\n";
    }
    if (out.len == 0) return "";
    return "\n// Header-only functions, forced to exist as symbols.\n" ++ out;
}

/// `int (*cppbindgen_f0)(int, int) = &ns::add;`, or the member-pointer form.
/// The declared type is what picks one function out of an overload set.
fn pointerDecl(comptime f: ctype.Function, comptime name: []const u8) []const u8 {
    const target = " = &" ++ cppsrc.pathName(f.path) ++ ";";
    const ret = cppsrc.typeName(f.ret) ++ " ";
    const params = cppsrc.paramList(f.params);
    if (f.this) |t| {
        const cls = cppsrc.pathName(f.path[0 .. f.path.len - 1]);
        return ret ++ "(" ++ cls ++ "::*" ++ name ++ ")" ++ params ++ (if (t.is_const) " const" else "") ++ target;
    }
    return ret ++ "(*" ++ name ++ ")" ++ params ++ target;
}

/// A virtual function's address is a vtable slot, not the definition, so the
/// address form would force nothing. A qualified call names the definition.
fn virtualStub(comptime f: ctype.Function, comptime types: []const Entry, comptime name: []const u8) []const u8 {
    const cls = aliasOf(f.path[0 .. f.path.len - 1], types, f);
    const self = cls ++ (if (f.this.?.is_const) " const" else "") ++ "* self";
    const args = cppsrc.argList(f.params);
    const sep = if (f.params.len == 0) "" else ", ";
    return "void " ++ name ++ "(" ++ self ++ sep ++ innerParams(f.params) ++ ") { (void)(self->" ++
        cls ++ "::" ++ f.path[f.path.len - 1].name ++ "(" ++ args ++ ")); }";
}

/// Constructing an object is the only way to name a constructor.
fn ctorStub(comptime f: ctype.Function, comptime types: []const Entry, comptime name: []const u8) []const u8 {
    const cls = aliasOf(f.path[0 .. f.path.len - 1], types, f);
    const init = if (f.params.len == 0) "" else "(" ++ cppsrc.argList(f.params) ++ ")";
    return "void " ++ name ++ "(" ++ innerParams(f.params) ++ ") { " ++ cls ++ " tmp" ++ init ++ "; (void)tmp; }";
}

/// A destructor named through a typedef, which is how a template-id or a
/// qualified name can appear in a destructor call at all. The call is
/// qualified: an unqualified one on a class with a virtual destructor is a
/// vtable dispatch, which names no definition and so forces nothing.
fn dtorStub(comptime f: ctype.Function, comptime types: []const Entry, comptime name: []const u8) []const u8 {
    const cls = aliasOf(f.path[0 .. f.path.len - 1], types, f);
    return "void " ++ name ++ "(" ++ cls ++ "* self) { self->" ++ cls ++ "::~" ++ cls ++ "(); }";
}

fn innerParams(comptime params: []const CType) []const u8 {
    if (params.len == 0) return "";
    const list = cppsrc.namedParamList(params);
    return list[1 .. list.len - 1];
}

/// The alias of a class the glue already named. A constructor or destructor
/// can only be spelled through one, so the class has to be in the manifest.
fn aliasOf(comptime path: []const ctype.Component, comptime types: []const Entry, comptime f: ctype.Function) []const u8 {
    const key = ctype.pathKey(path);
    inline for (types, 0..) |e, i| if (std.mem.eql(u8, ctype.pathKey(e.info.path), key)) return alias(i);
    @compileError(ctype.pathKey(f.path) ++ ": the glue needs a Zig type for '" ++ key ++
        "'; add it to the manifest's modules or types");
}

/// The layout and ABI facts a binding asserts, checked against the real class.
fn checks(comptime types: []const Entry) []const u8 {
    comptime var out: []const u8 = "";
    inline for (types, 0..) |e, i| {
        const a = alias(i);
        const cxx = cppsrc.pathName(e.info.path);
        if (@typeInfo(e.T) != .@"opaque") {
            out = out ++ assert("sizeof(" ++ a ++ ") == " ++ ctype.decimal(@sizeOf(e.T)), cxx ++ " is not " ++ ctype.decimal(@sizeOf(e.T)) ++ " bytes, the size of " ++ @typeName(e.T));
            out = out ++ assert("alignof(" ++ a ++ ") == " ++ ctype.decimal(@alignOf(e.T)), cxx ++ " does not have alignment " ++ ctype.decimal(@alignOf(e.T)) ++ ", the alignment of " ++ @typeName(e.T));
            out = out ++ abiCheck(e, a, cxx);
            if (e.offsets) out = out ++ offsetChecks(e, a, cxx);
        }
    }
    if (out.len == 0) return "";
    return "\n// What the bindings claim about each class, checked against it.\n" ++ out;
}

/// `ClassAbi` in the C++ compiler's own terms. The category decides how a
/// class travels by value, so getting it wrong corrupts every by-value call;
/// nothing on the Zig side can catch that, and this does.
fn abiCheck(comptime e: Entry, comptime a: []const u8, comptime cxx: []const u8) []const u8 {
    if (@typeInfo(e.T) == .@"enum") return "";
    // Itanium's "non-trivial for the purposes of calls": a class travels by
    // pointer once any of its copy constructor, move constructor, or
    // destructor is non-trivial.
    const trivial_for_calls = "__is_trivially_constructible(" ++ a ++ ", " ++ a ++ " const&) && " ++
        "__is_trivially_constructible(" ++ a ++ ", " ++ a ++ "&&) && " ++
        "__is_trivially_destructible(" ++ a ++ ")";
    return switch (e.info.abi) {
        .c_struct => assert(
            "__is_trivial(" ++ a ++ ") && __is_standard_layout(" ++ a ++ ")",
            cxx ++ " is not a plain C struct, so cpp_abi = .c_struct is wrong for it; it needs .trivial_copy or .managed_copy",
        ),
        // MSVC returns a class in a register only when it could have been
        // written in C, so a genuinely trivial class is .c_struct, not this.
        .trivial_copy => assert(
            trivial_for_calls ++ " && !__is_trivial(" ++ a ++ ")",
            cxx ++ " does not match cpp_abi = .trivial_copy; it is either a plain C struct (.c_struct) or non-trivial to copy (.managed_copy)",
        ),
        .managed_copy => assert(
            "!(" ++ trivial_for_calls ++ ")",
            cxx ++ " is trivial to copy, so cpp_abi = .managed_copy is wrong for it; it needs .c_struct or .trivial_copy",
        ),
    };
}

/// One `offsetof` per field, which is what catches a member the binding is
/// missing, has in the wrong order, or spells at the wrong width.
fn offsetChecks(comptime e: Entry, comptime a: []const u8, comptime cxx: []const u8) []const u8 {
    if (@typeInfo(e.T) != .@"struct") return "";
    comptime var out: []const u8 = "";
    inline for (@typeInfo(e.T).@"struct".field_names) |field| {
        if (field[0] == '_') continue;
        const off = ctype.decimal(@offsetOf(e.T, field));
        out = out ++ assert("offsetof(" ++ a ++ ", " ++ field ++ ") == " ++ off, cxx ++ "::" ++ field ++ " is not at offset " ++ off ++ ", where " ++ @typeName(e.T) ++ " puts it");
    }
    return out;
}

fn assert(comptime cond: []const u8, comptime message: []const u8) []const u8 {
    return "static_assert(" ++ cond ++ ", \"cpp-bindgen: " ++ message ++ "\");\n";
}

test "render checks a class" {
    const mod = struct {
        pub const Counter = extern struct {
            n: c_int,
            pub const cpp_name = "ns::Counter";
        };
        pub const get: Signature = .{ .name = "get", .ret = c_int, .this = *const Counter };
    };
    const out = comptime render(.{ .headers = &.{"counter.h"}, .modules = &.{mod} });
    try expectContains(out, "#include \"counter.h\"");
    try expectContains(out, "typedef ns::Counter cppbindgen_t0;");
    try expectContains(out, "int (ns::Counter::*cppbindgen_f0)() const = &ns::Counter::get;");
    try expectContains(out, "static_assert(sizeof(cppbindgen_t0) == 4,");
    try expectContains(out, "static_assert(alignof(cppbindgen_t0) == 4,");
    try expectContains(out, "static_assert(offsetof(cppbindgen_t0, n) == 0,");
    try expectContains(out, "static_assert(__is_trivial(cppbindgen_t0) && __is_standard_layout(cppbindgen_t0),");
}

test "render instantiates a specialization and forces a constructor" {
    const mod = struct {
        pub const Cell = extern struct {
            val: c_int,
            pub const cpp_template = cpp.Template{ .name = "tpl::Cell", .args = &.{.{ .type = c_int }} };
            pub const cpp_abi: cpp.ClassAbi = .managed_copy;
        };
        pub const ctor: Signature = .{ .name = "*", .args = &.{c_int}, .this = *Cell };
        pub const dtor: Signature = .{ .name = "~", .this = *Cell };
    };
    const out = comptime render(.{ .headers = &.{"<cell>"}, .modules = &.{mod} });
    try expectContains(out, "#include <cell>");
    try expectContains(out, "template struct tpl::Cell<int>;");
    try expectContains(out, "void cppbindgen_f0(int a0) { cppbindgen_t0 tmp(a0); (void)tmp; }");
    try expectContains(out, "void cppbindgen_f1(cppbindgen_t0* self) { self->cppbindgen_t0::~cppbindgen_t0(); }");
    try expectContains(out, "static_assert(!(__is_trivially_constructible(cppbindgen_t0, cppbindgen_t0 const&)");
}

test "render skips padding fields and honours opt-outs" {
    const mod = struct {
        pub const Poly = extern struct {
            _vptr: *const anyopaque,
            n: c_int,
            _pad: [4]u8,
            pub const cpp_name = "ns::Poly";
            pub const cpp_abi: cpp.ClassAbi = .managed_copy;
        };
        pub const Vec = extern struct {
            v: [3]f32,
            pub const cpp_template = cpp.Template{ .name = "tpl::vec", .args = &.{ .{ .int = 3 }, .{ .type = f32 } } };
            pub const cpp_no_instantiate = true;
            pub const cpp_no_offsets = true;
        };
        pub const f: Signature = .{ .name = "f", .ret = c_int, .this = *Poly, .virtual = true };
    };
    const out = comptime render(.{ .modules = &.{mod} });
    try expectContains(out, "static_assert(offsetof(cppbindgen_t0, n) == 8,");
    try std.testing.expect(std.mem.indexOf(u8, out, "_vptr") == null);
    try std.testing.expect(std.mem.indexOf(u8, out, "template struct tpl::vec") == null);
    try std.testing.expect(std.mem.indexOf(u8, out, "offsetof(cppbindgen_t1") == null);
    try expectContains(out, "void cppbindgen_f0(cppbindgen_t0* self) { (void)(self->cppbindgen_t0::f()); }");
}

fn expectContains(comptime haystack: []const u8, comptime needle: []const u8) !void {
    if (std.mem.indexOf(u8, haystack, needle) == null) {
        std.debug.print("\nmissing:\n{s}\nin:\n{s}\n", .{ needle, haystack });
        return error.NotFound;
    }
}
